In [1]:
import numpy as np

In [2]:
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])

In [3]:
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45])

In [4]:
dodatek = np.array([4,5,9,10,23,-14,55,13])

In [5]:
dodatek

array([  4,   5,   9,  10,  23, -14,  55,  13])

In [10]:
razem = np.concatenate((ar,dodatek))

In [11]:
razem

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [14]:
ar = razem
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [30]:
#z_zamiana_na_liste
ar.tolist().index(9)

14

In [31]:
#z_nonzero
np.nonzero(ar == 9)

(array([14], dtype=int64),)

In [32]:
#z_where
np.where(ar == 9)

(array([14], dtype=int64),)

In [33]:
#mniejsze_od_zera_z_nonzero
np.nonzero(ar < 0 )

(array([ 2,  5,  8, 17], dtype=int64),)

In [34]:
#mniejsze_od_zera_z_where
np.where(ar < 0)

(array([ 2,  5,  8, 17], dtype=int64),)

In [38]:
#z where
ar[np.where(ar <0)]

array([ -3, -10, -98, -14])

In [37]:
# z nonzero
ar[np.nonzero(ar<0)]

array([ -3, -10, -98, -14])

In [39]:
np.mean(ar)

12.1

In [44]:
np.around(np.mean(ar), decimals=1)

12.1

In [46]:
ar_abs = np.absolute(ar)
ar_abs

array([ 1,  2,  3,  6,  7, 10, 88, 43, 98, 17, 39, 45,  4,  5,  9, 10, 23,
       14, 55, 13])

In [47]:
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [52]:
ar_p = np.cbrt(ar_abs)
ar_p

array([ 1.        ,  1.25992105,  1.44224957,  1.81712059,  1.91293118,
        2.15443469,  4.44796018,  3.50339806,  4.61043629,  2.57128159,
        3.39121144,  3.5568933 ,  1.58740105,  1.70997595,  2.08008382,
        2.15443469,  2.84386698,  2.41014226,  3.80295246,  2.35133469])

In [72]:
np.sum(ar_p)

50.589999999999996

In [73]:
ar_p = np.around(ar_p, decimals=2)
ar_p

array([ 1.  ,  1.26,  1.44,  1.82,  1.91,  2.15,  4.45,  3.5 ,  4.61,
        2.57,  3.39,  3.56,  1.59,  1.71,  2.08,  2.15,  2.84,  2.41,
        3.8 ,  2.35])

In [84]:
np.sum(ar_p)

50.589999999999996

In [85]:
#dlaczego???? skąd ta ilość cyfr po przecinku?
#sprawdzam ar_p
ar_p

array([ 1.  ,  1.26,  1.44,  1.82,  1.91,  2.15,  4.45,  3.5 ,  4.61,
        2.57,  3.39,  3.56,  1.59,  1.71,  2.08,  2.15,  2.84,  2.41,
        3.8 ,  2.35])

In [86]:
ar_sq = np.square(np.sum(ar_p))
ar_sq

2559.3480999999997

In [87]:
type(ar_sq)

numpy.float64

In [90]:
ar_sq = int(ar_sq)
ar_sq

2559

In [91]:
type(ar_sq)

int