In [1]:
import numpy as np

In [2]:
los = np.random.RandomState(100)

In [3]:
liczby = los.randint(-100,100,1000000)

In [4]:
liczby

array([-92, -76, -33, ...,  90, -61,  61])

###### Z1: Stwórz wektor wartości powiększony o 20 - używamy list comprehensions!

In [5]:
#liczby20 = liczby + 20
liczby_plus_20 = np.array([each+20 for each in liczby])
liczby_plus_20

array([-72, -56, -13, ..., 110, -41,  81])

In [6]:
np.around(np.mean(liczby_plus_20))

20.0

###### Z2: Wektor takich wartości, które są większe od zera

In [7]:
#liczby_wieksze_od_0 = liczby[liczby > 0]
wieksze_od_0 = np.array([each for each in liczby if each > 0])
wieksze_od_0

array([ 3, 76, 38, ..., 54, 90, 61])

In [8]:
#sprawdzam:
#liczby_wieksze_od_0

In [9]:
wieksze_od_0.mean()

50.012424740562949

###### Z3: Wektor wartości podniesionych do kwadratu, ale tylko jeśli oryginalna wartość była większa od 50

In [10]:
#liczby_wieksze_od_50_do_kwadratu = liczby[liczby > 50] **2
#liczby_wieksze_od_50_do_kwadratu

In [11]:
wieksze_od_50_do_kwadratu = np.array([each **2 for each in liczby if each > 50])
wieksze_od_50_do_kwadratu

array([5776, 6400, 3025, ..., 2916, 8100, 3721])

In [12]:
wieksze_od_50_do_kwadratu.mean()

5827.5576118868166

###### Z4: Wektor wartości, w którym:
1. wartości większe od zera są podniesione do kwadratu
2. pozostałe wartości pozostają niezmienione
3. zapisz do zmiennej lc

In [13]:
Ic = np.array([each **2 if each > 0 else each for each in liczby ])
Ic

array([ -92,  -76,  -33, ..., 8100,  -61, 3721])

In [14]:
Ic.mean()

1620.457557

###### Z5: Wektor wartości parzystych z wektora lc

In [15]:
parzyste = np.array([each for each in Ic if each % 2 == 0])
parzyste

array([ -92,  -76, 5776, ..., 3136, 2916, 8100])

In [16]:
parzyste.mean()

1596.3932955079904

###### Z6: Wektor wartości nieparzystych z wektora lc

In [17]:
nieparzyste = np.array([each for each in Ic if each % 2 != 0])
nieparzyste

array([ -33,    9,  -13, ...,   -9,  -61, 3721])

In [18]:
nieparzyste.mean()

1644.4895939720388

###### Z7: Słownik, w którym hasłem jest liczba a znaczeniem informacja czy dana liczba jest parzysta czy nieparzysta

In [19]:
#sprawdzam czy umiem uzyskać boolean
czy_parzyste = Ic % 2 == 0
czy_parzyste

array([ True,  True, False, ...,  True, False, False], dtype=bool)

In [20]:
#spradzam czy się zgadza
Ic

array([ -92,  -76,  -33, ..., 8100,  -61, 3721])

In [21]:
Slownik_parzystosci = {each : each % 2 == 0 for each in Ic}
Slownik_parzystosci

{-100: True,
 -99: False,
 -98: True,
 -97: False,
 -96: True,
 -95: False,
 -94: True,
 -93: False,
 -92: True,
 -91: False,
 -90: True,
 -89: False,
 -88: True,
 -87: False,
 -86: True,
 -85: False,
 -84: True,
 -83: False,
 -82: True,
 -81: False,
 -80: True,
 -79: False,
 -78: True,
 -77: False,
 -76: True,
 -75: False,
 -74: True,
 -73: False,
 -72: True,
 -71: False,
 -70: True,
 -69: False,
 -68: True,
 -67: False,
 -66: True,
 -65: False,
 -64: True,
 -63: False,
 -62: True,
 -61: False,
 -60: True,
 -59: False,
 -58: True,
 -57: False,
 -56: True,
 -55: False,
 -54: True,
 -53: False,
 -52: True,
 -51: False,
 -50: True,
 -49: False,
 -48: True,
 -47: False,
 -46: True,
 -45: False,
 -44: True,
 -43: False,
 -42: True,
 -41: False,
 -40: True,
 -39: False,
 -38: True,
 -37: False,
 -36: True,
 -35: False,
 -34: True,
 -33: False,
 -32: True,
 -31: False,
 -30: True,
 -29: False,
 -28: True,
 -27: False,
 -26: True,
 -25: False,
 -24: True,
 -23: False,
 -22: True,
 -21: False,

###### Z8: Słownik, w którym hasłem jest liczba a znaczeniem informacja czy dana liczba jest podzielna czy niepodzielna przez 16. Zapisz do zmiennej s16

In [22]:
s16 = {each : each % 16 == 0 for each in Ic}
s16

{-100: False,
 -99: False,
 -98: False,
 -97: False,
 -96: True,
 -95: False,
 -94: False,
 -93: False,
 -92: False,
 -91: False,
 -90: False,
 -89: False,
 -88: False,
 -87: False,
 -86: False,
 -85: False,
 -84: False,
 -83: False,
 -82: False,
 -81: False,
 -80: True,
 -79: False,
 -78: False,
 -77: False,
 -76: False,
 -75: False,
 -74: False,
 -73: False,
 -72: False,
 -71: False,
 -70: False,
 -69: False,
 -68: False,
 -67: False,
 -66: False,
 -65: False,
 -64: True,
 -63: False,
 -62: False,
 -61: False,
 -60: False,
 -59: False,
 -58: False,
 -57: False,
 -56: False,
 -55: False,
 -54: False,
 -53: False,
 -52: False,
 -51: False,
 -50: False,
 -49: False,
 -48: True,
 -47: False,
 -46: False,
 -45: False,
 -44: False,
 -43: False,
 -42: False,
 -41: False,
 -40: False,
 -39: False,
 -38: False,
 -37: False,
 -36: False,
 -35: False,
 -34: False,
 -33: False,
 -32: True,
 -31: False,
 -30: False,
 -29: False,
 -28: False,
 -27: False,
 -26: False,
 -25: False,
 -24: False,
 -2

###### Z9: Wektor wartości podzielnych przez 16 ze słownika s16

In [23]:
s16.values()

dict_values([False, False, False, False, False, False, True, False, False, True, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, True, True, False, False, False, False, False, False, True, False, False, False, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, True, Fa

In [24]:
#próbowałam tak, ale nie wychodzi - muszę jeszcze popróbować
#podzielne_przez_16 = np.array([each for each in s16.keys() if s16.values() == True])

In [25]:
podzielne_przez_16 = np.array([each for each in s16.keys() if each % 16 == 0])
podzielne_przez_16

array([5776, 6400, 1936,   64, 1024,    0,  -96, 5184, 8464, 7056,  -32,
       7744,  -64,  -16, 9216,  256, 2704,  -80, 1600, 2304, 4624, 3136,
        144,  -48, 4096,  784,   16,  576,  400, 3600, 1296])

In [26]:
podzielne_przez_16.mean()

2518.1935483870966

###### Z10: Wektor wartości niepodzielnych przez 16 ze słownika s16

In [27]:
niepodzielne_przez_16 = np.array([each for each in s16.keys() if each % 16 != 0])
niepodzielne_przez_16

array([ -92,  -76,  -33,    9,  -13,  -21, 1444,   -6,   -2,  -47,  -34,
        -86,  -66, 1849,   49,  -40,  -42, 1369,   -7,  -14,  900, 3025,
       3481,  841, 1681,   -9, 7569, 1225,  -51, 5625, 8649,  -39, 6889,
       9801,  -20,  -98,  441,   25, 2209,  -37, 6561,  -73,  -44,  169,
       3364,  -53, 4489,   81,  -62,  -82, 3844,  -83,  -28,  -87,   36,
        -70, 6084,  -22, -100, 7225,  961,  -30,  -57,  -95,  -29, 4900,
         -5,  196,  361,  -24,  -67,    4, 2500, 8100,  -50, 3969, 2601,
        -91,  -79, 2809, 6724,  -94, 4225,  484, 7396,  -61,  -49,  -55,
        -11, 5329,  -65,  -84,  -88, 2116,   -8,  -56,  -43,  729,  -27,
       1089, 6241,  -10, 9025,  -23,  225,  -72, 2025,  -26,  -18,  -19,
        289,  -75, 8836,  -89,    1,  -78,  -45,  -58,  -17, 7921,  -63,
         -1,  -38, 5929,  121, 1521,  -71, 2916,  -15,  676,  529,  -52,
        -68,  -60, 1764,  -59,  -35,  -90,  -74, 3721,  -12,  -41,  -85,
       1156,  100, 5476, 9409,  -36,  -25,   -4,  -

In [28]:
niepodzielne_przez_16.mean()

1451.1005917159764